name: 'Rhino Yak Package Manager'
description: 'Deploy packages straight from GitHub to the Yak package manager'
inputs:
  build-path:  # id of input
    description: 'The path to the build directory'
    required: true
    default: './dist'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
