name: 'Yak Package Manager Action'
description: 'Automate publishing using the Yak package manager'
inputs:
  build-directory:  # path of the build directory
    description: 'The path to the buil diectory'
    required: true
    default: './dist'
  version:
    description: 'The version of the package'
    required: true
#runs:
#  using: 'node12'
#  main: 'index.js'


runs:
  using: "composite"
  steps: 
    - run: cd ${{ github.workspace }} && curl -fSLo yak.exe https://files.mcneel.com/yak/tools/latest/yak.exe && .\yak.exe version
      shell: pwsh
    - run: ls ${{ inputs.build-directory }}
      shell: pwsh
    - run: cd ${{ inputs.build-directory }} && ${{ github.workspace }}\yak.exe build --version "$Env:NBGV_SemVer2" --platform win && cd ${{ github.workspace }}
      shell: pwsh
    - run: echo "Simulating push"
      shell: pwsh



  #      # Then use the version string
  #    - uses: dotnet/nbgv@master
  #      with:
  #        setAllVars: true

#  - name: Download the package
#     run: cd ${{ github.action_path }} && curl -fSLo yak.exe https://files.mcneel.com/yak/tools/latest/yak.exe && .\yak.exe version
#     shell: pwsh
     
#  - name: Build Yak package
#     run: cd ${{ github.action_path }} && cd ${{ inputs.build-directory }} && ${{ github.action_path }}\yak.exe build --version "$Env:NBGV_SemVer2" --platform win && cd ${{ github.action_path }}
#       shell: pwsh

     
#  - name: List Contence After
#     run: dir ${{ github.action_path }}${{ inputs.build-directory }}

#  - name: Publish package
#     - run: Get-ChildItem ${{ inputs.build-directory }} -Filter *.yak | ForEach-Object -Process {.\yak.exe push  $_}
#     run: echo "Simulating push"
#       shell: pwsh
     

